language: java
jdk:
- oraclejdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
    secure: csjoYYvSn6q4FLjNbVOudrDUCjKa1OZLnoqcTXoWv2oDq+LDfwg8HgRGoQp3F3GRXIaf9Fdgp45CMDGKT3DLLoj74jbK6fvLcOOUj4wAzMCEi0N6l3aqn/Y+863/gN1gmLHOLTRb+VFK3jOjSDXqMF4Xli8+vGKtJxnCr3EvIz0=
    secure: Pw01KCxXCHHDBHddg1PifepaIkefdVzWh3H4tCoyCg3zO/xI5bqwof/E6+NxDQ9pWYQVVF/o9ZPEuiAzX8/42mKnCFR/FPS8ihzjkb8yn4OPSXza78IXMCE35PbuUUVIOmFoCEnIHHbO03distow+r4lY8pJjcWE4fMQDb/NpPE=
