language: java
jdk:
- oraclejdk7
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: V/R3NwWPG9UqW6PC5rhfa1eYsvRSHve84es7/7SIWMdu971b3NzOAQj+pRw9WcrhtfuOBUNocAGlUQwJVU3ZVtua28Ed/Fb8bSyx9Se7dmwyx3HL6DWdBgQpAtG64oB70gqXZc6ZQ2kUKn95sUkvoeOZmEFoCIG3zTeEXWG2x4E=
  - secure: VMpk3K/1UJYTFKq9XZ2Il9imrnmUOVmvz0y51qUVkccFFvIML/g4Mv277Cv9pC3aQzy/rDn0m3M8zJH7Z1N9la16N0qOMjZeZSEhCLOn2VX4zdAPvMBNlYg6bpuWl613qtAJe2djc41GUx/luoX6hnGyxnmcG8mIc4nWZgEKG0Q=
